theme: Hexo-Theme-Yun
deploy:
  type: git
  repo: https://github.com/yung03/yung03.github.io # 比如：https://github.com/YunYouJun/yunyoujun.github.io
  branch: master # 默认使用 master 分支
  message: Update Hexo Static Content # 你可以自定义此次部署更新的说明

